name: 'Build & Publish Docker Container'

inputs:
  registry:
    required: true
  image_name:
    required: true
  dockerfile_path:
    required: true
  github_token:
    required: true

runs:
  using: 'composite'
  steps:
  - name: Log in to the GitHub Container Registry
    uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    with:
      registry: ${{ inputs.registry }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    with:
      images: ${{ inputs.registry }}/${{ inputs.image_name }}

  - name: Build and push Docker image
    uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    with:
      context: ${{ inputs.dockerfile_path }}
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
