name: Kernel Buildbot Docker Container

on:
  push:
    paths:
    - .github/workflows/**
    - build/kernel/**

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-docker-image
        with:
          dockerfile_path: ./build/kernel
          registry: ghcr.io
          image_name: skyline-operating-system/kernel-buildbot
          github_token: ${{ secrets.GITHUB_TOKEN }}
